"""phase_4_advanced_config

Revision ID: 393d2d788f4b
Revises: fffb3b29c6c3
Create Date: 2026-10-10 18:35:12.496887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393d2d788f4b'
down_revision: Union[str, Sequence[str], None] = 'fffb3b29c6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('timeout_seconds', sa.Integer(), server_default='10', nullable=False))
    op.add_column('services', sa.Column('failure_threshold', sa.Integer(), server_default='2', nullable=False))
    op.add_column('services', sa.Column('expected_status_codes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'expected_status_codes')
    op.drop_column('services', 'failure_threshold')
    op.drop_column('services', 'timeout_seconds')
    # ### end Alembic commands ###
