"""add_webhook_url_to_users

Revision ID: 3b2bff231ea6
Revises: 393d2d788f4b
Create Date: 2026-10-10 19:16:24.531681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2bff231ea6'
down_revision: Union[str, Sequence[str], None] = '393d2d788f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webhook_url')
    # ### end Alembic commands ###
