"""phase_1_service_state_and_indexes

Revision ID: 6e5c41f72812
Revises: 19e3f2466209
Create Date: 2026-10-10 10:41:33.469235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5c41f72812'
down_revision: Union[str, Sequence[str], None] = '19e3f2466209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_checks_service_checked_at', 'checks', ['service_id', 'checked_at'], unique=False)
    op.drop_constraint(op.f('checks_service_id_fkey'), 'checks', type_='foreignkey')
    op.create_foreign_key(None, 'checks', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_incidents_service_is_open', 'incidents', ['service_id', 'is_open'], unique=False)
    op.add_column('services', sa.Column('status', sa.String(), nullable=True))
    op.add_column('services', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('last_latency_ms', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('failure_count', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('last_status_code', sa.Integer(), nullable=True))
    op.create_index('ix_services_owner_next_check', 'services', ['owner_id', 'next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_owner_next_check', table_name='services')
    op.drop_column('services', 'last_status_code')
    op.drop_column('services', 'failure_count')
    op.drop_column('services', 'last_latency_ms')
    op.drop_column('services', 'next_check_at')
    op.drop_column('services', 'last_checked_at')
    op.drop_column('services', 'status')
    op.drop_index('ix_incidents_service_is_open', table_name='incidents')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'checks', type_='foreignkey')
    op.create_foreign_key(op.f('checks_service_id_fkey'), 'checks', 'services', ['service_id'], ['id'])
    op.drop_index('ix_checks_service_checked_at', table_name='checks')
    # ### end Alembic commands ###
