"""phase_1_strict_constraints_and_indexes

Revision ID: fffb3b29c6c3
Revises: 6e5c41f72812
Create Date: 2026-10-10 12:17:00.975807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fffb3b29c6c3'
down_revision: Union[str, Sequence[str], None] = '6e5c41f72812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE services SET status = 'PENDING' WHERE status IS NULL")
    op.execute("UPDATE services SET failure_count = 0 WHERE failure_count IS NULL")
    op.execute("UPDATE services SET next_check_at = NOW() WHERE next_check_at IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'next_check_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('services', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_services_active_next_check', 'services', ['is_active', 'next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_active_next_check', table_name='services')
    op.alter_column('services', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('services', 'next_check_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
